// ASKS
export const LOAD_ASKS = "LOAD_ASKS";
export const LOAD_MY_ASKS = "LOAD_MY_ASKS";
export const UNLOAD_ASKS = "UNLOAD_ASKS";
export const LOAD_ASK = "LOAD_ASK";
export const UNLOAD_ASK = "UNLOAD_ASK";
export const CREATE_ASK = "CREATE_ASK";
export const DELETE_ASK = "DELETE_ASK";
export const UPDATE_ASK = "UPDATE_ASK";

// BIDS
export const LOAD_BIDS = "LOAD_BIDS";
export const LOAD_MY_BIDS = "LOAD_MY_BIDS";
export const UNLOAD_BIDS = "UNLOAD_BIDS";
export const LOAD_BID = "LOAD_BID";
export const UNLOAD_BID = "UNLOAD_BID";
export const CREATE_BID = "CREATE_BID";
export const DELETE_BID = "DELETE_BID";

// TEMPORARY ASK
export const SET_ASK_COIN = "SET_ASK_COIN";
export const SET_ASK_VOLUME = "SET_ASK_VOLUME";
export const SET_ASK_PRICE = "SET_ASK_PRICE";
export const SET_ASK_LATITUDE = "SET_ASK_LATITUDE";
export const SET_ASK_LONGITUDE = "SET_ASK_LONGITUDE";
export const SET_ASK_CONTACT_INFO = "SET_ASK_CONTACT_INFO";
export const SET_ASK_USE_CURRENT_LOCATION = "SET_ASK_USE_CURRENT_LOCATION";
export const SET_ASK_VOLUME_IN_USD = "SET_ASK_VOLUME_IN_USD";
export const RESET_ASK = "RESET_ASK";

// TEMPORARY BID
export const SET_BID_COIN = "SET_BID_COIN";
export const SET_BID_VOLUME = "SET_BID_VOLUME";
export const SET_BID_PRICE = "SET_BID_PRICE";
export const SET_BID_LATITUDE = "SET_BID_LATITUDE";
export const SET_BID_LONGITUDE = "SET_BID_LONGITUDE";
export const SET_BID_USE_CURRENT_LOCATION = "SET_BID_USE_CURRENT_LOCATION";
export const SET_BID_CONTACT_INFO = "SET_BID_CONTACT_INFO";
export const SET_BID_VOLUME_IN_USD = "SET_BID_VOLUME_IN_USD";
export const RESET_BID = "RESET_BID";

// LAYERS
export const SET_LAYER = "SET_LAYER";
export const OPEN_LAYER = "OPEN_LAYER";

// SESSION
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const REGISTER_USER = "REGISTER_USER";
export const USER_FROM_TOKEN = "USER_FROM_TOKEN";
export const SESSION_LOAD = "SESSION_LOAD";
export const CURRENT_LOCATION_LOAD = "CURRENT_LOCATION_LOAD";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

// APP
export const LOAD_NAV_HEIGHT = "LOAD_NAV_HEIGHT";
export const LOAD_HEADER_HEIGHT = "LOAD_HEADER_HEIGHT";
export const LOAD_WINDOW_HEIGHT = "LOAD_WINDOW_HEIGHT";
export const LOAD_WINDOW_WIDTH = "LOAD_WINDOW_WIDTH";
export const SET_MARKET_VIEW = "SET_MARKET_VIEW";
export const SET_SUBSCRIBED = "SET_SUBSCRIBED";
export const SET_SW_REGISTRATION = "SET_SW_REGISTRATION";


// FILTERS
export const SET_FILTER_DISTANCE = "SET_FILTER_DISTANCE";
export const SET_FILTER_COIN = "SET_FILTER_COIN";
export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const SET_FILTER_PRICE = "SET_FILTER_PRICE";
export const SET_FILTER_ITEMS = "SET_FILTER_ITEMS";
export const SET_FILTER = "SET_FILTER";

// OFFERS
export const LOAD_OFFERS_BY_USER = "LOAD_OFFERS_BY_USER";
export const LOAD_OFFER = "LOAD_OFFER";
export const LOAD_OFFERS_BY_ASK = "LOAD_OFFERS_BY_ASK";
export const LOAD_OFFERS_BY_BID = "LOAD_OFFERS_BY_ASK";
export const UNLOAD_OFFERS = "UNLOAD_OFFERS";
export const PATCH_OFFER = "PATCH_OFFER";
export const DELETE_OFFER = "DELETE_OFFER";

// TEMPORARY OFFER
export const SET_OFFER_VOLUME = "SET_OFFER_VOLUME";
export const SET_OFFER_VOLUME_IN_USD = "SET_OFFER_VOLUME_IN_USD";
export const SET_CONTACT_INFO = "SET_CONTACT_INFO";
export const RESET_OFFER = "RESET_OFFER";

// TRANSACTIONS
export const LOAD_TRANSACTIONS = "LOAD_TRANSACTIONS";
export const UNLOAD_TRANSACTIONS = "UNLOAD_TRANSACTIONS";
export const LOAD_TRANSACTION = "LOAD_TRANSACTION";
export const UNLOAD_TRANSACTION = "UNLOAD_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const COMPLETE_TRANSACTION = "COMPLETE_TRANSACTION";
export const CANCEL_TRANSACTION = "CANCEL_TRANSACTION";

// ERRORS
export const SET_ERROR = "SET_ERROR";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

// METRICS
export const CURRENCY_NAMES_LOAD = "CURRENCY_NAMES_LOAD";
export const LAST_PRICE_LOAD = "LAST_PRICE_LOAD";
